package Threads;

public class ResultTask extends Thread {
    public void run(){
        System.out.println("Result generated by:"+Thread.currentThread().getName());
    }

    static void main(String[] args) {
        ResultTask t1 = new ResultTask();
        t1.run();//normal execution -> Always the main thread
        t1.start();//Multi threading
        //Start() internally calls run()
        //Thread cannot be started twice

    }

}
